# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master #workflow triggered by push and pull requests to the main branch

name: Test-Script #name of the workflow

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }} 

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) #

    strategy:
      fail-fast: false # allows the test to continue running even though it fails in one OS
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'} #test is done on windows and macOS environment and on the latest versions

    env: #config environment
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true # will not cause warning messages during calls to install packages to become errors
      _R_CHECK_FORCE_SUGGESTS_: false #prevents installation of suggested dependencies
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2 #checks out code on job environment so we can use it to run tests

      - uses: r-lib/actions/setup-r@v1 #set up r environment for specified versions in the matrix
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version") #not sure if needed
        shell: Rscript {0} 

      - name: Test against test script
        run: |
          chmod +x /R/test_script.R
          /R/test_script.R
        shell: Rscript {0}

      - name: Upload check results #shows error and warning messages
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
