on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Test-Script

jobs:
  build:
    runs-on: ${{ matrix.config.os }} 

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) 

    strategy:
      fail-fast: false 
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'} 

    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@master 
        with:
          r-version: ${{ matrix.config.r }}
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Test against test script
        run: Rscript test_script.R
        shell: Rscript {0}
