# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master #workflow triggered by push and pull requests to the main branch

name: Test-Script #name of the workflow

jobs:
  build:
    runs-on: ${{ matrix.config.os }} 

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) #

    strategy:
      fail-fast: false # allows the test to continue running even though it fails in one OS
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'} #test is done on windows and macOS environment and on the latest versions

    steps:
      - uses: actions/checkout@v2 #checks out code on job environment so we can use it to run tests

      - uses: r-lib/actions/setup-r@v1 #set up r environment for specified versions in the matrix
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Test against test script
        run: |
          Rscript test_script.R
        shell: Rscript {0}
